theme: minima
title: Raunak's Blog
author: raunak-shr
email: raunak.dvm@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  My blog is intended for those users who desire to keep themselves
  updated with the latest devlopments in the field of Science and technology. Your
  ideas to any errors or bugs are always welcomed. Thanks!

# social links
twitter_username: raunak_exe # DO NOT include the @ character, or else the build will fail!
github_username:  raunak-shr # DO NOT include the @ character, or else the build will fail!

show_excerpts: true # set to false to remove excerpts on the homepage
